export const projects = {
    "burger-builder": {
        name: "Burger Builder",
        technologyIcon: "React",
        summary: "Denne portfolio-siden er laget av meg selv ... ",
        discipline: ['Front-end'],
        screenshots: ['burgerBuilder1.png', 'burgerBuilder2.png', 'burgerBuilder3.png'],
        siteURL: "https://www.sarahsvedenborg.no",
        gitHubURL: "https://www.github.com",
        problem: "Create an interface for people to order burgers",
        demography: "Other like-minded people",
        technology: [['Rammeverk', 'React'], ['Backend', 'Firebase'], ['Hosting', 'Netlify']],
        lessons: "",
        other: "Prosjeket er laget som en del av et React-kurs på udemy.com med Maximillian Swartzmüller. Her har jeg bare fokusert på kodingen. Alt av design er tatt rett frakurset. Se retro-burger-builder for min redesign av prosjektet.",
    },
    "retro-burger-builder": {
        name: "Retro Burger Builder",
        technologyIcon: "React",
        summary: "Designet og brukeropplevelsen ble endret i dette prosjektet ",
        discipline: ['UX'],
        screenshots: ['forBarna1.png', 'forBarna2.png', 'forBarna3.png'],
        siteURL: "https://www.sarahsvedenborg.no",
        gitHubURL: "https://www.github.com",
        problem: "Create an interface for people to order burgers",
        demography: "Other like-minded people",
        technology: [['Rammeverk', 'React'], ['Backend', 'Firebase'], ['Hosting', 'Netlify'], ['internal state management', 'Redux']],
        lessons: "firebase backend, react router, redux, react hooks, lazy loading, project/file organization, css modules",
        other: "Front-end koden er basert på burger-builder prosjeket som er laget som en del av et React-kurs på udemy.com med Maximillian Swartzmüller. I dette prosjektet er GUI-et redesignet for et freshere inntrykk og en smidigere brukeropplevelse.",
    },
    "for-barna": {
        name: "ForBarna.no",
        technologyIcon: "@/assets/Vue.svg",
        summary:
            "Et nettsted som samler pedagogiske spill jeg har laget til barna.",
        discipline: ['UX', 'Front-end'],
        screenshots: ['forBarna1.png', 'forBarna2.png', 'forBarna3.png'],
        siteURL: "https://www.forbarna.no",
        gitHubURL: "https://github.com/sarahsvedenborg/forbarna",
        problem: "Et nettsted som samler alle spillene vi lager til barna hvor de kan øve på skolearbeidet sitt.",
        demography: "Barn 6-9 år.",
        technology: [['Rammeverk', 'Vue.js'], ['Backend', 'Firebase'], ['Hosting', 'Netlify']],
        lessons: "Touch on iPad. iPad first",
        other: "",
    },
    "portfolio": {
        name: "sarahsvedenborg.no",
        technologyIcon: "Vue",
        summary: "Denne portfolio-siden er laget av meg selv ... ",
        discipline: ['UX', 'Front-end'],
        screenshots: ['portfolio1.png', 'portfolio2.png', 'portfolio3.png'],
        siteURL: "https://www.sarahsvedenborg.no",
        gitHubURL: "https://www.github.com",
        problem: "Create a portfolio to showcase who I am and what I can do",
        demography: "Other like-minded people",
        technology: [['Rammeverk', 'Vue.js'], ['Backend', 'Firebase'], ['Hosting', 'Netlify'], ['UI design', 'Sketch']],
        lessons: "Lasy-loading, single file components, vue router, i18n, custom grid, custom UI components, css animations, folder structure, responsive design",
        other: "",
    },
    "beauty-board": {
        name: "Beauty Board",
        technologyIcon: "React",
        summary: "Dette er en trello lignende app som ... ",
        discipline: ['UX', 'Front-end'],
        screenshots: ['forBarna1.png', 'forBarna2.png', 'forBarna3.png'],
        siteURL: "https://www.sarahsvedenborg.no",
        gitHubURL: "https://www.github.com",
        problem: "Implement trello-ish app from scratch",
        demography: "Project planners",
        technology: [['Rammeverk', 'React'], ['Backend', 'Firebase'], ['Hosting', 'Netlify'], ['state management', 'Redux']],
        lessons: "virtual list for backup, drag and drop, redux, react-router, react hooks,",
        other: "Denne har jeg laget helt fra scratch",
    },


}